### ISSUE TITLE
ImportError: No module named nfqueue

### ISSUE THREAD

**Issue by Plumatester** [csandker/spnegoDown#1]
I know this is a stretch, but any chance this repo might get ported to python3 someday?

The issue I am having is that nfqueue simply does not install on my system. Not even the package I downloaded directly from Debian and tried to install using dpkg -i <pkg>.

My python2 version is 2.7.18, which according to the error output below is supposed to be in between the required versions.

└─# dpkg -i python-nfqueue_0.6-1+b1_amd64.deb
Selecting previously unselected package python-nfqueue.
(Reading database ... 330813 files and directories currently installed.)
Preparing to unpack python-nfqueue_0.6-1+b1_amd64.deb ...
Unpacking python-nfqueue (0.6-1+b1) ...
dpkg: dependency problems prevent configuration of python-nfqueue:
 python-nfqueue depends on python (<< 2.8); however:
  Package python is not installed.
 python-nfqueue depends on python (>= 2.7~); however:
  Package python is not installed.
 python-nfqueue depends on python:any (<< 2.8).
 python-nfqueue depends on python:any (>= 2.7.5-5~).

dpkg: error processing package python-nfqueue (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 python-nfqueue

Any ideas?

**Comment by csandker** [comment]
puh... we'll you're right this code is quite old and as I haven't used it in quite a while I currently have no plans to upgrade it to Python3.

I guess it might be possible to find and install the required `nfqueue` version, but depending on your requirements and use case it might not be worth it. 
Sorry that I don't have a better answer. The silver lining is: The code is not very complex and `nfqueue`  is not  a critical center piece, but merely used to redirect and and queue packets. If you want to invest the time to get this code in a modern shape it might work out of the box with [NetfilterQueue for Python3](https://pypi.org/project/NetfilterQueue/) (Side note to that: If I would re-work this code I would also evaluate other options as `nfqueue` as there might be better ways to implement this - back in the day this code was meant as a PoC and I needed a quick and easy way to setup the traffic redirection).

**Comment by Plumatester** [comment]
First of all, thank you for answering, and quickly too!

Before going down that route, are you aware of any other tools with the same functionality as your tool? Or a better question would be, is this tool still viable in modern Active Directory environments?

I am no expert in python, but I can give it a try. Do you know of any modules in particular that you think might cause issues when porting the code over to Python 3?

Thanks again!

**Comment by csandker** [comment]
Hi,

As of now I do not know of any other tool that attempts to downgrade SPNEGO, sorry.
To your question whether it is still viable: I haven't used this tool in a while, but I guess this attack still works and SPNEGO can still be downgraded, given the right attack scenario I'd say this attack is still viable and could be useful.
The other side of the story is though: The reason that I've not used this in years is, because I never needed a downgrade of SPNEGO in a Man-in-the-middle position, as in such a privileged position other attacks - most of all relay attacks - worked without altering SPNEGO.

So before getting your hands on re-working this, I would raise the question whether it is just for the sake of playing around with it (in which case I would encourage you to go that route) or if this is just meant to be a driver to exploit a specific attack scenario, in which case easier/quicker options might exist.

Lastly to your question about any show stoppers that I'd see when upgrading this: I don't see any. However, if you're new to Python you will find that Python3 often returns 'raw' bytes instead of strings and errors when applying string operations to 'raw' bytes. But if Python is a language that you feel could be valuable for you, there is nothing better than getting your hands dirty and work through all the pitfalls that might come along the way.
Re-working this tool will also require to set up a more or less 'realistic' network scenario to verify your code does actually work.

Hope this helps.
